version: '3.8'

services:
  sentiment-app:
    container_name: sentiment-app
    build: .
    command: 'python manage.py run -h 0.0.0.0'
    ports:
      - 4000:5000
    depends_on:
      - sentiment-db

  sentiment-db:
    platform: linux/x86_64
    container_name: sentiment-db
    image: mysql
    ports:
      - "32000:3306"
    restart: always
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    volumes:
      - mysql_data:/var/lib/mysql
    
volumes:
  mysql_data: