name: remote ssh commands to deploy
on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set env var (prod)
      if: endsWith(github.ref, '/main')
      run: echo "DEPLOY_SH=deploy-prod.sh" >> $GITHUB_ENV
    - name: Set env var (dev)
      if: endsWith(github.ref, '/develop')
      run: echo "DEPLOY_SH=deploy-develop.sh" >> $GITHUB_ENV
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script_stop: true
        script: |
          cd ${{ secrets.PROJECT_PATH }}
          sh ${{ env.DEPLOY_SH }} 
